/**
 * Converts a base64 string to a Uint8Array for Web Push applicationServerKey
 */
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding)
    .replace(/-/g, "+")
    .replace(/_/g, "/");

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

/**
 * Checks whether Web Push is supported by the current browser.
 */
export function isPushSupported(): boolean {
  return (
    typeof window !== "undefined" &&
    "serviceWorker" in navigator &&
    "PushManager" in window &&
    "Notification" in window
  );
}

/**
 * Requests push permission and subscribes the user's browser.
 */
export async function subscribeUserToPush(): Promise<{
  success: boolean;
  permission: NotificationPermission;
  error?: string;
}> {
  if (!isPushSupported()) {
    return {
      success: false,
      permission: "denied",
      error: "Push notifications are not supported in this browser.",
    };
  }

  const vapidPublicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;
  if (!vapidPublicKey) {
    return {
      success: false,
      permission: Notification.permission,
      error: "VAPID public key is not configured.",
    };
  }

  // 1. Request notification permission
  const permission = await Notification.requestPermission();
  if (permission !== "granted") {
    return {
      success: false,
      permission,
      error: "Notification permission was not granted.",
    };
  }

  // 2. Wait for Service Worker registration
  const registration = await navigator.serviceWorker.ready;

  // 3. Subscribe with PushManager
  try {
    const convertedKey = urlBase64ToUint8Array(vapidPublicKey);
    let subscription = await registration.pushManager.getSubscription();

    if (!subscription) {
      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: convertedKey as BufferSource,
      });
    }

    const subJson = subscription.toJSON();
    if (!subJson.endpoint || !subJson.keys?.p256dh || !subJson.keys?.auth) {
      return {
        success: false,
        permission,
        error: "Invalid subscription details generated by browser.",
      };
    }

    // 4. Send subscription to server
    const res = await fetch("/api/push/subscribe", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        endpoint: subJson.endpoint,
        keys: {
          p256dh: subJson.keys.p256dh,
          auth: subJson.keys.auth,
        },
      }),
    });

    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      return {
        success: false,
        permission,
        error: data.error || "Failed to register subscription with server.",
      };
    }

    return { success: true, permission: "granted" };
  } catch (err: unknown) {
    const error = err as Error;
    return {
      success: false,
      permission,
      error: error.message || "Failed to subscribe to push notifications.",
    };
  }
}

/**
 * Unsubscribes the current device from push notifications.
 */
export async function unsubscribeUserFromPush(): Promise<{
  success: boolean;
  error?: string;
}> {
  if (!isPushSupported()) {
    return { success: true };
  }

  try {
    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.getSubscription();

    if (subscription) {
      const endpoint = subscription.endpoint;
      await subscription.unsubscribe();

      await fetch("/api/push/subscribe", {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ endpoint }),
      });
    }

    return { success: true };
  } catch (err: unknown) {
    const error = err as Error;
    return {
      success: false,
      error: error.message || "Failed to unsubscribe from notifications.",
    };
  }
}
